config/routes.rb
Rails.application.routes.draw do

  resources :eateries

  root 'sessions#new'
  get 'signup' => 'users#new', as: :signup
  post 'signup' => 'users#create'
  
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:index, :new, :show, :create, :destroy]

  get 'signin' => 'sessions#new', as: :signin
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy', as: :signout
  

end

app/models/eatery.rb
class Eatery < ActiveRecord::Base
	
	has_many :favorites
	has_many :users, through: :favorites
	belongs_to :users
	 

	def self.search(search)
    if search
      #case insensitive
      where('name ILIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :eatery
	belongs_to :user

	validates :eatery_id, presence: true, uniqueness: { case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :favorites
	has_many :eateries, through: :favorites
	belongs_to :eateries

	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	
	before_save { self.email = email.downcase }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
									  uniqueness: { case_sensitive: false}
	validates :password, length: { minimum: 6 }


	before_create :create_remember_token
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController
	helper_method :sort_column, :sort_direction

	def index
		@eateries = Eatery.search(params[:search]).order(sort_column + " " + sort_direction)
		@asc = "http://www.clipartbest.com/cliparts/nTX/EGB/nTXEGBLTB.png"
		@desc = "http://upload.wikimedia.org/wikipedia/en/e/e0/Black_Down_Arrow.png"
	end
 
	def show	
		@eatery = Eatery.find(params[:id])
	end


	def new	
		if signed_in?
			@eatery = Eatery.new
		else
			redirect_to signin_path
		end
	end

	def create
		@eatery = Eatery.new(eatery_params)

		if @eatery.save
			@eateries = Eatery.all
			redirect_to @eatery
		else
			redirect_to "new"
		end
	end

	def edit
		@eatery = Eatery.find(params[:id])
	end

	def update
		@eatery = Eatery.find(params[:id])
		if @eatery.update_attributes(eatery_params)
			redirect_to @eatery
		else
			render "edit"
		end
	end

	def destroy
		@eatery = Eatery.find(params[:id])
		@eatery.favorites.each {|f| f.destroy }
		@eatery.destroy
		redirect_to eateries_path
	end

	private
		def eatery_params
			params.require(:eatery).permit(:name, :address, :phone_num, :image_url, :website, :rating, :drive_thru)
		end

		def sort_column
			Eatery.column_names.include?(params[:sort]) ? params[:sort] : "name"
		end

		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
		end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	# Show all the favorite eateries of the user.
	def index
		@favorites = Favorite.all
	end

	# Create a new favorite
	def new
		if signed_in?
			@eatery = Eatery.find(params[:format])
			@favorite = Favorite.new
			@eatery_id = params[:format]
			@user_id = current_user.id
		else
			redirect_to signin_path
		end
	end

	# Create the favorite
	def create
		@favorite = Favorite.new(favorite_params)

		if @favorite.save
			@favorites = Favorite.all
			redirect_to @favorite
		else
			render 'new'
		end
	end

	def show
		@favorite = Favorite.find(params[:id])
		@eatery = Eatery.find(@favorite.eatery_id)
	end

	# Delete a favorite eatery.
	def destroy
		@favorite = Favorite.find(params[:id])
  		@favorite.destroy
  		redirect_to favorites_path
	end
	
	private
		def favorite_params
			params.require(:favorite).permit(:name, :description, :user_id, :eatery_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to current_user
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user  
    else
      # flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :edit, :update, :destroy]
	before_action :signed_in_user, except: [:new, :create]
	before_action :correct_user, except: [:new, :create]
	
	# def index
	# 	@users = User.all
	# end

	def show
		#@user = User.find(params[:id])
	end


	def new
		if current_user
			redirect_to current_user
		else 
			@user = User.new
		end
	end

	def create
		@user = User.new(user_params)

		if @user.save
			sign_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update    
		if @user.update_attributes(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		if @user.destroy
			redirect_to root_url
		else
			render 'show'
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation)
		end

		def find_user
			@user = User.find(params[:id])
		end

		def correct_user
			find_user
			redirect_to(current_user) unless current_user?(@user)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper



def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to "#{title} <i class='#{direction == "desc" ? "glyphicon glyphicon-circle-arrow-down" : "glyphicon glyphicon-circle-arrow-up"}'></i>".html_safe, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
end
end 

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in_user
    unless signed_in?
      redirect_to signin_url
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/eateries/_show.html.erb
    <!-- Show Eatery you are favoriting -->
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4" style="font-size:40px">
      <div>
          <%= @eatery.name %> 
          <br/>
          <%= link_to(@eatery.website, target: '_blank') do %>
            <%= image_tag(@eatery.image_url, width: '100%', alt: 'Image Url') %>
          <% end %>
          <br/>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
      <div>
        <strong>Address:</strong>
        <p> <%= @eatery.address %> </p>
        <br>
        <iframe src=<%= @eatery.map_url %>> </iframe>
        </div>
        <br/>
    </div>
    <div class="col-xs-6 col-sm-4 col-md-4">
        <div>
          <strong>Phone Number:</strong>
          <%= @eatery.phone_num %>
          <br>
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-4 col-md-4">
      <div>
         <strong>Rating:</strong>
          <% if @eatery.rating.to_i > 0 %> 
            <% @eatery.rating.to_i.times do |i| %>
              <span class="glyphicon glyphicon-star"></span>
            <% end %> 
          <% else %>
            No Rating
          <% end %>
        </div>
      </div>
    <div class="col-xs-6 col-sm-3 col-md-2">
      <div>
          <strong>Drive Thru:</strong>
           <% if @eatery.drive_thru %> 
            Yes
           <% else %>
            No
           <% end %>
      </div>
    </div>
    <br/>
    <!-- End Show Eatery you are favoriting -->

app/views/eateries/edit.html.erb
<div class="center">


<h1 class="new_field">Edit Eatery</h1>
<%= form_for @eatery do |f| %>
  <div class="new_field"><%= f.label :name %>: </div>
  <div class="new_input"><%= f.text_field :name %><br/> </div>
  <div class="new_field"><%= f.label :image_url %> </div>
  <div class="new_input"><%= f.text_field :image_url %> <br/> </div>
  <div class="new_field"><%= f.label :address %>: </div>
  <div class="new_input"><%= f.text_field :address %><br/> </div>
  <div class="new_field"><%= f.label :phone_num %>: </div>
  <div class="new_input"><%= f.text_field :phone_num %><br/>  </div>
  <div class="new_field"><%= f.label :website %>: </div>
  <div class="new_input"><%= f.text_field :website %><br/>  </div>
  <div class="new_field"><%= f.label :rating %>: </div>
  <div class="new_input"><%= f.text_field :rating %><br/>  </div>
  <div class="new_field"><%= f.label :drive_thru %>: </div>
  <div class="new_input"><%= f.text_field :drive_thru %><br/>  </div>
  <div class="new_field"><%= f.label :map_url %>: </div>
  <div class="new_input"><%= f.text_field :map_url %><br/>  </div>
  <br/>
  <div id="sub_input"> <%= f.submit %></div> <br/>
<% end %>

 
<p><%= link_to "All Eateries", eateries_path %></p>
<p><%= link_to "Delete", @eatery, method: "delete" %></p> 
<p><%= link_to "New", new_eatery_path %></p>

</div>

app/views/eateries/index.html.erb
 

<h1 class="main"> Eateries </h1> 

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <%= form_tag eateries_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <p class="search">
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %> 
  <br/>
</div>

<div class="table-responsive col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <table class="table table-hover" width="100%">

    <thead>
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= sortable "address" %></th>
        <th><%= sortable "phone_num" %></th>
        <th><%= sortable "rating" %></th>
        <th><%= sortable "drive_thru" %></th>

        <th colspan="9"></th>   

      </tr>
    </thead>

    <tbody>
      <% @eateries.each do |eatery| %>
        <tr class= "tBody">
          <td>
            <%= link_to(eatery) do %>
              <%= eatery.name %>
              <p><img class="eatery-logo" src=<%= eatery.image_url %>></p>
            <% end %>
          </td> 
          <td><%= eatery.address %></td>
          <td><%= eatery.phone_num %></td>
          <td>
              <% if eatery.rating.to_i > 0 %> 
                <% eatery.rating.to_i.times do |i| %>
                  <span class="glyphicon glyphicon-star"></span>
                <% end %> 
              <% else %>
                No Rating
              <% end %>
          </td>
          <td>
             <% if eatery.drive_thru %> 
              Yes
             <% else %>
              No
             <% end %>
          </td>
          <td>
            <%= link_to(new_favorite_path(eatery)) do %>
              <span class="glyphicon glyphicon-heart"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>


<p><%= link_to "Add New Eatery", new_eatery_path, class: "" %></p>

app/views/eateries/new.html.erb
 
<%= form_for @eatery do |f| %>
  <div class="new_field"><%= f.label :name %>: </div>
  <div class="new_input"><%= f.text_field :name %><br/> </div>
  <div class="new_field"><%= f.label :image_url %> </div>
  <div class="new_input"><%= f.text_field :image_url %> <br/> </div>
  <div class="new_field"><%= f.label :address %>: </div>
  <div class="new_input"><%= f.text_field :address %><br/> </div>
  <div class="new_field"><%= f.label :phone_num %>: </div>
  <div class="new_input"><%= f.text_field :phone_num %><br/>  </div>
  <div class="new_field"><%= f.label :website %>: </div>
  <div class="new_input"><%= f.text_field :website %><br/>  </div>
  <div class="new_field"><%= f.label :rating %>: </div>
  <div class="new_input"><%= f.text_field :rating %><br/>  </div>
  <div class="new_field"><%= f.label :drive_thru %>: </div>
  <div class="new_input"><%= f.text_field :drive_thru %><br/>  </div>
  <div class="new_field"><%= f.label :map_url %>: </div>
  <div class="new_input"><%= f.text_field :map_url %><br/>  </div>
  <br/>
  <div id="sub_input"> <%= f.submit %></div> <br/>
<% end %>


 

<div class="new_input"><%= link_to "All Eateries", eateries_path %></div>

app/views/eateries/show.html.erb
<div class="container-fluid main">
	<div class="row">
		<%= render "eateries/show" %>
	</div>
	<br/>


  <div> <%= link_to(new_favorite_path(@eatery)) do %>
      <span class="glyphicon glyphicon-heart"></span>
    <% end %>
  </div>


<p><%= link_to "Edit Eatery", edit_eatery_path %></p>
<p><%= link_to "Show All Eateries", eateries_path %></p>
<p><%= link_to "Delete Eatery", @eatery, method: "delete" %></p>

	

</div>

app/views/favorites/index.html.erb
<h1 class="main"> Favorites </h1> 



<div class="table-responsive col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <table class="table table-hover" width="100%">

    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Eatery</th>
        
      </tr>
    </thead>

    <tbody>

       <% @favorites.each do |fav| %>
         <tr class="tBody">
            <td><%= fav.name %></td>
            <td><%= fav.description %></td>
            <td><%= link_to "Show", fav %></td>
            <td><%= link_to "Remove From Favorites", fav, method: "delete" %></td>
        </tr>
      <% end %>

    </tbody>

  </table>
</div> 

app/views/favorites/new.html.erb
<div class="row"> 
  <div class="span6 offset3">

    <%= render "eateries/show" %>

    <!-- Favorites Form -->
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 center">
    <h2> Add <%= @eatery.name %> to Favorites </h2>

    <%= form_for @favorite do |f| %>
      <% if @favorite.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this eatery from being favorited:</h2>

          <ul>
          <% @favorite.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <%= f.label :name, :value => @eatery.name %>:<br/>
      <span class="new_input"><%= f.text_field :name %><br/></span>

      <%= f.label :description %>:<br/>
      <span class="new_input"><%= f.text_field :description %><br/><br/></span>

      <%= f.hidden_field :user_id, :value => @user_id%>
      <%= f.hidden_field :eatery_id, :value => @eatery_id %>

      <%= f.submit "Add To Favorites", class: "btn btn-large btn-primary" %><br/>
    <% end %>
    
    <p><%= link_to "Cancel", eateries_path %></p>

    </div>
    <!-- End Favorites Form -->
  </div>
</div>

app/views/favorites/show.html.erb
<h1>Name: <%= @favorite.name %></h1>
<h1>Description: <%= @favorite.description %></h1>
<hr/>

<%=render 'eateries/show'%>


<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<br/><br/>
<p><%= link_to "See Eateries Close to Me", eateries_path %></p>
<p><%= link_to "See All Favorites", favorites_path %> <p>
<br/><br/>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 
<head>
  <title>Midnight Munchies</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'data-turbolinks-track' => true %>
<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>


	<!-- Start Bootstrap Nav Bar -->
	<div id="nav">
		<nav class="navbar navbar-default" role="navigation">
		  	<div class="container-fluid">

		  		<div class="navbar logos"> 
		  			<%= link_to(eateries_path) do %>
  						<%= image_tag("https://s3.amazonaws.com/uploads.hipchat.com/140618/1019233/tqhnDjPhsOFYT8G/Logo_Big.png", height: '100%') %>
					<% end %>	
					<%= link_to "idnight Munchies", eateries_path %>

					<%= link_to(signin_path) do %>
					<img id="settings" src="https://cdn3.iconfinder.com/data/icons/setting/100/settings_gear_1-512.png"/>
					<% end %>	
				
					<%= link_to(new_eatery_path) do %>
						<span id="add-eatery" class="glyphicon glyphicon-plus"/>
					<% end %>	

				</div>

			</div><!-- end div.container-fluid -->
		</nav>
	</div>
	<!-- End Bootstrap Nav Bar -->

		<div class="page-wrap">
			<%= yield %>
		</div>
		
		<footer class="site-footer col-xs-12 col-sm-12 col-md-12 col-lg-12">
		</footer>


</body>

</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, value: "" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="center">
        <p><%= f.label :email %>
        <p><span class="new_input"><%= f.text_field :email %><br/></span>

        <p><%= f.label :password %>
        <p><span class="new_input"><%= f.password_field :password, value: "" %><br/></span>

        <p><%= f.label :password_confirmation %>
        <p><span class="new_input"><%= f.password_field :password_confirmation, value: ""%><br/></span>

        <p class="center"><%= f.submit "Update yourself", class: "btn btn-large btn-primary" %> <br/>
      </div>
    <% end %>

    <p class="center"><%= link_to "Cancel", @user %></p>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table> 
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Remember Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.remember_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to "Eatery Page", eateries_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="center">
      <p><%= f.label :email %></p>
      <p class="new_input"><%= f.text_field :email %><br/></p>

      <p><%= f.label :password %></p>
      <p class="new_input"><%= f.password_field :password %><br/></p>

      <p><%= f.label :password_confirmation %></p>
      <p class="new_input"><%= f.password_field :password_confirmation %><br/></p>

      <p><%= f.submit "Sign Up", class: "btn btn-large btn-primary" %></p>

      </div>
    <% end %>

    <div class="center"> <%= link_to "Or Sign In", signin_path %> </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<p><%= link_to "Edit", edit_user_path %></p>
<p><%= link_to "Delete Your Account", @user, method: 'delete' %></p>
<p><%= link_to "See Eateries Close to Me", eateries_path %></p>
<p><%= link_to "See My Favorites", favorites_path %></p>
<p><%= link_to "Sign Out", signout_path , method: "delete" %><p> 